# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  name: aws

steps:
- script: aws s3 cp s3://downloads-us-east-2/amplifyconfiguration.json amplifyconfiguration.json
  workingDirectory: $(Build.Repository.LocalPath)
  displayName: amplifyconfiguration.json
- script: aws s3 cp s3://downloads-us-east-2/awsconfiguration.json awsconfiguration.json
  workingDirectory: $(Build.Repository.LocalPath)
  displayName: awsconfiguration.json
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Todo'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
